---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'test'
Parameters:
  BucketName:
    Type: String
    Default: "test"
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
